export enum InstructionParameters {
    OUTPUT = "OUTPUT",
    TABLE = "TABLE",
    GROUP = "GROUP",
    METER = "METER",    
    QUEUE = "QUEUE",
    L0MODIFICATION = "L0MODIFICATION",
    L1MODIFICATION = "L1MODIFICATION",
    L2MODIFICATION = "L2MODIFICATION",
    L3MODIFICATION = "L3MODIFICATION",
    L4MODIFICATION = "L4MODIFICATION"

}